meilisearch/meilisearch-rails

- lib/meilisearch-rails.rb
- meilisearch-rails.gemspec
> Remove Algolia

- Gemfile
- lib/meilisearch-rails.rb
> Upgrade meilisearch ruby

- README.md
- lib/meilisearch-rails.rb
- lib/meilisearch/pagination/kaminari.rb
- spec/integration_spec.rb
- spec/spec_helper.rb
- spec/utilities_spec.rb
> Transform hash symbols old syntax into modern syntax

- README.md
- lib/meilisearch-rails.rb
- playground/app/models/book.rb
- spec/integration_spec.rb
- Rename `Filters` into `Filter`
- Rename `attributes_for_faceting` into `filterable_attributes`
- Fix tests and Add missing tests according to new features
> Update related to v0.21.0

- lib/meilisearch/pagination/kaminari.rb
Works fine for me. Need more confirmation from ruby2 users.
Fixes #60
> Fix kaminari initialize error in Ruby3

- Gemfile
- README.md
- playground/app/models/book.rb
- spec/integration_spec.rb
Should be merged once MeiliSearch v0.22.0 is released
> Update MeiliSearch version in README (v0.22.0)

- lib/meilisearch/version.rb
Why is it breaking?
- https://github.com/meilisearch/meilisearch-rails/pull/99
- https://github.com/meilisearch/meilisearch-rails/pull/92
Other relevant changes:
- https://github.com/meilisearch/meilisearch-rails/pull/96
- https://github.com/meilisearch/meilisearch-rails/pull/94
> Update version for the next release (v0.4.0)

- lib/meilisearch/version.rb
> Update version for the next release (v0.4.1)

- lib/meilisearch/rails/version.rb
Relevant changes:
- #106 
- #108
> Update version for the next release (v0.5.0)

- README.md
Fixes #117 
Thank you so much for contributing to MeiliSearch!
> update readme to document sortable_attributes option

- meilisearch-rails.gemspec
> Fix Meilisearch naming in the gemspec

- .github/workflows/tests.yml
- lib/meilisearch-rails.rb
> fix ms_job loading path

- lib/meilisearch/rails/version.rb
> Update version for the next release (v0.5.1)

- .code-samples.meilisearch.yaml
Add the code samples according to #135
Fixes #135
> Create .code-samples.meilisearch.yml with landing page sample

- docker-compose.yml
- lib/meilisearch/rails/version.rb
* Remove duplicated gem versions from the gemspec/Gemfile (#149) @brunoocasali
* Update sidekiq worker to job in readme (#137) @jmarsh24
* Fix rubocop unintentional CI error (#144) @brunoocasali
Thanks again to  @brunoocasali, @curquiza, @jmarsh24 ! 🎉
> Update version for the next release (v0.5.2)

- lib/meilisearch-rails.rb
Fixes #163 
- [X ] Does this PR fix an existing issue?
- [ X] Have you read the contributing guidelines?
- [ X] Have you made sure that the title is accurate and descriptive of the changes?
> Check for Sequel::Model instead of only ::Sequel

- .github/workflows/tests.yml
- Dockerfile
- docker-compose.yml
- playground/Gemfile
- playground/config/initializers/meilisearch.rb
Our playground was not working properly if accessed inside of the docker container.
> Fix playground with docker environment

- Gemfile
- README.md
- lib/meilisearch-rails.rb
- lib/meilisearch/rails/configuration.rb
- lib/meilisearch/rails/null_object.rb
- spec/integration_spec.rb
- spec/spec_helper.rb
> Control state of the access to the HTTP

- .rubocop_todo.yml
- README.md
- lib/meilisearch-rails.rb
- spec/integration_spec.rb
- spec/support/active_record_classes.rb
Fixes #<issue_number>
- Since the pagination setting was added in v0.28. I have changed it so that setting can be done in Model.
> Since the pagination setting was added in v0.28. I have changed it so that setting can be done in Model.

- playground/app/controllers/search_controller.rb
- playground/app/models/song.rb
- playground/config/initializers/pagy.rb
- playground/db/migrate/20221128210955_create_songs.rb
- playground/db/schema.rb
- playground/db/seeds.rb
We currently support pagy, but it is not tested or written anywhere. This PR adds the possibility to try it in the playground mode.
> Add pagy setup to playground

- README.md
I stumbled upon this lack of information. So I'm adding it :)
> Mention in the README about `formatted` method

- meilisearch-rails.gemspec
- Adds support for Meilisearch 1.2.0
- [✅] Have you read the contributing guidelines?
- [✅] Have you made sure that the title is accurate and descriptive of the changes?
> Update meilisearch-ruby to 0.24.0

- .github/workflows/tests.yml
- Gemfile
- README.md
- spec/spec_helper.rb
> Add codecov

- playground/app/controllers/songs_controller.rb
- playground/app/models/author.rb
- playground/app/models/song.rb
- playground/app/views/songs/index.html.erb
- playground/db/migrate/20230905213930_create_authors.rb
- playground/db/schema.rb
- playground/db/seeds.rb
- playground/test/fixtures/authors.yml
- playground/test/models/author_test.rb
Trying to reproduce this issue #281
> Add author relationship on Song model

- spec/spec_helper.rb
> Provide a way to disable coverage by DISABLE_COVERAGE env

- .github/workflows/gempush.yml
- .github/workflows/pre-release-tests.yml
- .github/workflows/tests.yml
> Update CI to use Ubuntu 22.04

- spec/integration_spec.rb
> Remove redundant calls to sleep in tests

- spec/spec_helper.rb
- spec/support/2_method_helpers.rb
- spec/support/active_record_classes.rb
> Properly clean up indexes after test suite runs

- .github/workflows/gempush.yml
> Add ruby/setup-ruby action & use ruby 2.7

- lib/meilisearch/rails/version.rb
> Update version for the next release (v0.11.1)

- lib/meilisearch/rails/version.rb
> Update version for the next release (v0.12.0)

- lib/meilisearch/rails/version.rb
We should ship the fix to #352 ASAP, and also add support for #351, I believe that would mean a minor version in semver.
> Update version for the next release (v0.13.0)

- lib/meilisearch/rails/pagination/kaminari.rb
- spec/pagination/kaminari_spec.rb
Fixes [#<issue_number>](https://github.com/meilisearch/meilisearch-rails/issues/375)
Fixes this error if no results are found (nullobject is made into zero)
```
TypeError:
no implicit conversion of MeiliSearch::Rails::NullObject into Integer
```
- [ x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [ x] Have you read the contributing guidelines?
- [ x] Have you made sure that the title is accurate and descriptive of the changes?
> For kaminari fixes zero results bug

- lib/meilisearch/rails/version.rb
Apply hotfix: https://github.com/meilisearch/meilisearch-rails/pull/387
> Update version for the next release (v0.14.2)

- lib/meilisearch/rails/version.rb
Last release before we rename the main module on 0.15.
> Update version for next release (v0.14.3)
