meilisearch/meilisearch-rails

README.md

Hey there! Thanks for maintaining meilisearch-rails!
Here are some fixes to the Ruby code examples in the README, as well as some minor reformatting to make examples more consistent between each other and feel more Ruby-esque.

Fix Ruby syntax in README

---

README.md
lib/meilisearch-rails.rb
playground/app/models/book.rb
spec/integration_spec.rb

In order to be more Ruby-esque, this uses snake_case options in favor of the camelCase options.
The camelCase syntax is kept for backwards compatibility.

Accept snake_case for meilisearch options

---

lib/meilisearch/utilities.rb

This issue cause `rails meilisearch:reindex` task failed.
log
```
NoMethodError: undefined method `ms_reindex' for ProjectFile:Class
Did you mean?  ms_reindex!
must_reindex?
ms_index
ms_index!
```

Fix undefined method in reindex_all_models

---

README.md
lib/meilisearch/configuration.rb
meilisearch-rails.gemspec
spec/configuration_spec.rb

Add access to `timeout` and `max_retries` configuration options from Meilisearch’s HTTParty integration.

Add timeout and max_retries options

---

.github/release-draft-template.yml
.github/workflows/release-drafter.yml
Gemfile
README.md

Related to this issue: https://github.com/meilisearch/integration-guides/issues/117
This PR:
- gathers the changes related to the next MeiliSearch release (v0.21.0) so that this package is ready when the official release is out.
- might eventually contain test failures until the MeiliSearch v0.21.0 is out.
⚠️ This PR should NOT be merged until the next release of MeiliSearch (v0.21.0) is out.
Done:
- Changes related to v0.21.0 #58 #59
- Rename `Filters` into `Filter`
- Rename `attributes_for_faceting` into `filterable_attributes`
- Fix tests
- Add missing tests according to new features

Changes related to the next MeiliSearch release (v0.21.0)

---

README.md

It could be confusing for some people trying to setup the gem to see `YourMeiliSearchHost` as is, without knowing if adding the port is mandatory or not. This PR proposes to update the `meilisearch_host` key in the example configuration to note that it must be an URI if the port has to be set.

Update meilisearch_host in the conf example

---

Gemfile
lib/meilisearch-rails.rb
spec/spec_helper.rb

Add simplecov

---

Gemfile
README.md
lib/meilisearch-rails.rb
spec/integration_spec.rb

- Update meilisearch-ruby to v0.18.0
- Remove `get_or_create_index` method usage
- Changes regarding task API changes

Bump meilisearch-ruby (v0.18.0)

---

.github/workflows/tests.yml
bors.toml
lib/meilisearch/rails/railtie.rb
lib/meilisearch/rails/tasks/meilisearch.rake
playground/app/models/book.rb
playground/config/initializers/meilisearch.rb
spec/utilities_spec.rb

After defining the new Rails module to separate the logic between the meilisearch-ruby gem and this one
some `Rails` calls were incorrectly defined, they missed the `::` top-level reset to ignore the new `MeiliSearch::Rails` module.
Related to https://github.com/meilisearch/meilisearch-rails/issues/107
Fixes https://github.com/meilisearch/meilisearch-rails/issues/110

Fix Rails module calls inside the Meilisearch::Rails & Add smoke-test workflow step

---

.github/workflows/tests.yml
bors.toml
lib/meilisearch-rails.rb

This PR runs the integration tests against multiple Ruby versions just to make sure everything is compatible. 
Ruby versions need to be specified as strings so that they're parsed correctly. This is an issue with GitHub Actions: https://github.com/actions/runner/issues/849
It also adds Rails 7.0 to the test suite. Rails 5.2 isn't compatible with Ruby 3+ so it's excluded and can be dropped soon since it will be EOL.
This also now caches bundle install to speed up the CI for future runs. This required moving the flags to environment variables instead. https://github.com/ruby/setup-ruby#caching-bundle-install-automatically
I didn't know if it made sense to run the linter and smoke tests against multiple Ruby versions, so I left those out. Let me know if we should do that too.

Integration test rubies

---

.github/scripts/check-release.sh

After the big breaking change from 0.4.x to 0.5.x we should have to change the release script as well. Since I didn't change the latest release failed to be released.

Fix release version checker

---

README.md

Fixes #136
Workers have been depreciated in Sidekiq in favor of jobs. I have updated the readme so it reflects the change in order to prevent confusion.

Update sidekiq worker to job in readme

---

Gemfile
meilisearch-rails.gemspec
spec/spec_helper.rb

This removes the duplicated gem from the gemspec/Gemfile, I could not found a reason to be like this (I also checked for other well know gems and they only define dependencies in the gemspec, the Gemfile contains only dependencies for tests/development/benchmarks, etc - not shipped to the end-user).

Remove duplicated gem versions from the gemspec/Gemfile

---

.editorconfig
CONTRIBUTING.md
docker-compose.yml

This is part of the proposal to solve the https://github.com/meilisearch/integration-guides/issues/199
- Map to `/package` instead of `/app`.
- Remove `tty` and `stdin_open` in the `meilisearch` service (it is not required, only to the `package` service)
- Use `/package` everywhere.
- Add the `bundle` volume to map the dependencies and prevent downloading the same thing every time.
- Add `MEILI_NO_ANALYTICS` to prevent misleading the analytics numbers.

Improve Docker configuration in the package

---

README.md

- Remove camelCased attributes from the README
- Remove empty blocks
- Add blank line after `private` declaration

Remove camelCase attributes and empty blocks from README

---

README.md

Probably super-common to already have Model#search defined, especially if you're looking to switch from another library. 
Not sure about the title of the section added; open to suggestions.

Describe the use of `ms_` methods if things like `search` are already defined

---

lib/meilisearch-rails.rb
spec/integration_spec.rb

Add timeout errors to be kept when raise_on_failure is false

---

lib/meilisearch-rails.rb
spec/integration_spec.rb

Fix https://github.com/meilisearch/meilisearch-rails/issues/183
After this PR: https://github.com/meilisearch/meilisearch-rails/pull/49/files, we started to support snake_case options only in some attributes related to the Meilisearch engine like `sortableAttributes`.
And here https://github.com/meilisearch/meilisearch-rails/pull/154, I updated all the non-snake case attributes massively without checking if there was a missing spot like this.
TL;DR: 
`hitsPerPage` and `hits_per_page` should work fine now.

Add support for snake_case option in the pagination

---

lib/meilisearch-rails.rb
lib/meilisearch/rails/pagination/kaminari.rb
lib/meilisearch/rails/pagination/will_paginate.rb

The change was more straightforward than I expected. I removed the placeholder search and mapped the response from the Meilisearch server. Also, I ensure we will always have a `page = 1` when we have a `pagination_backend` set.
All the tests passed locally (by using meilisearch-ruby with the v0.30 changes). So I can assume, based on our coverage, we are good to go.

Add pagination handler using finite pagination

---

Gemfile

To prevent google searches everytime someone have to try a local `meilisearch-ruby` version in the rails gem.

Add a snippet to help testing this gem w/ local meilisearch-ruby version

---

CONTRIBUTING.md
docker-compose.yml
playground/Dockerfile
playground/Gemfile
playground/README.md
playground/app/controllers/search_controller.rb
playground/app/models/song.rb
playground/config/initializers/pagy.rb
playground/db/migrate/20221128210955_create_songs.rb
playground/db/schema.rb
playground/db/seeds.rb

Fixes https://github.com/meilisearch/meilisearch-rails/issues/155
- Add a README that explains how to use the playground
- Add docker-compose service `playground`, which is possible to run and see the front-end at `localhost:3000`.
- Fix playground required ruby and gem versions.

Improve playground setup

---

lib/meilisearch/rails/version.rb

This version makes this package compatible with Meilisearch v1.0.0 :tada:
Check out the changelog of [Meilisearch v1.0.0](https://github.com/meilisearch/meilisearch/releases/tag/v1.0.0) for more information on the changes.
* Update meilisearch-ruby to latest version `v0.22.0` (#231) @brunoocasali 
Thanks again @brunoocasali 🎉

Release v0.8.1

---

.github/workflows/pre-release-tests.yml
.github/workflows/tests.yml
Dockerfile
Gemfile
README.md
bors.toml

- Deprecate Ruby 2.6 and Ruby on Rails 5.2 (both are EOL since more than 1 year ago).
- Update meilisearch to 0.25.0
The minimum required version constraint in the gemspec is still 2.6 and will remain like that until we adopt a breaking feature for that version.
This way, we let the use decide when they will be able to move on!
Introduce a change from meilisearch-ruby 0.25.0. That will trigger a warning message when used with camelCase attributes.
Check the release changelog of meilisearch-ruby: https://github.com/meilisearch/meilisearch-ruby/releases/tag/v0.25.0

Deprecate Ruby 2.6 & Rails 5.2 officially

---

README.md
lib/meilisearch/rails/tasks/meilisearch.rake
lib/meilisearch/rails/templates/initializer.rb

New meilisearch:install task creates an initializer file
- adds a meilisearch:install task to create the meilisearch.rb initializer with template configuration
- adds changes to README.md file to include environment variables

Add install task

---

lib/meilisearch-rails.rb
spec/integration_spec.rb

Was getting warnings in tests and logs like so:
Non-conforming attributes: searchableAttributes, sortableAttributes
Attributes will be expected to be snake_case in future versions of Meilisearch Ruby.
Changed all instances of camel case to snake case to make warnings go away and to resolve the deprecations.

Changed camel case keywords to snake case

---

spec/integration_spec.rb
spec/support/active_record_classes.rb

Fixes #115 
- The behavior and methodology of the tests was left untouched wherever possible
- Issue #115 instructs to create a PR for each fixed file but `spec/integration_spec.rb` was the only file with any issues, so this PR should fix the whole suite
- Issue #115 does not fully instruct whether randomized testing should actually be enabled in the repo, so I left it disabled
- I ran the suite ~40 times after fixing everything (probably another ~40 times while fixing it) so there could still be issues I did not spot. My rationale was that the tests should ideally be refactored before (or while) going through them line by line and trying to spot any more errors.

Make integration_spec randomizable

---

lib/meilisearch/rails/pagination.rb
spec/integration_spec.rb

Fix error when warning about pagy configuration redundancy

---

lib/meilisearch-rails.rb
spec/integration_spec.rb

Fixes #271
- Changes `#ms_index!` to pass along the task hash provided by the meilisearch gem
- Adds tests for the three possible return types 
I'm new to this project, so I tried to keep the solution as unopinionated as possible. Please feel free to suggest changes to the implementation.

Add return value to ms_index!

---

lib/meilisearch-rails.rb
spec/integration_spec.rb

Fixes #329
May fix #328
- `SafeIndex` before I tried to fix #280 with #301 did not guarantee that its index exists at all, since `@index` was created asynchronously it was possible that `SafeIndex#settings` could be called on an index that does not exist.
This line:
https://github.com/meilisearch/meilisearch-rails/blob/29f59c88881b5a4b5a03d990f11d3aac220cd367/lib/meilisearch-rails.rb#L309 
was supposed return an empty hash when asked to fetch the settings of an index that does not exist, however `ApiError#code` is the meilisearch code (`"index_not_found"`) and not the http code (`404`). That line was therefore skipped and the `index_not_found` error was being propagated and caught by the `rescue nil` in:
https://github.com/meilisearch/meilisearch-rails/blob/e5ad4d1f10c078097bf211e4d3a6e1d4 …

Fix settings update regression

---

lib/meilisearch-rails.rb
lib/meilisearch/rails/multi_search.rb
lib/meilisearch/rails/multi_search/result.rb
lib/meilisearch/rails/utilities.rb
spec/multi_search/result_spec.rb
spec/multi_search_spec.rb

Fixes #254
I thought I'd make a draft PR to discuss and review API decisions. I discussed the method signature of a theoretical `multi_search` in https://github.com/meilisearch/meilisearch-rails/issues/254#issuecomment-1934245721, if there is no problem I will proceed with this one:
```ruby
MeiliSearch::Rails.multi_search(
'book_production' => {q: 'paper', class_name: 'Book', **book_options}, # Index with a model
Product => {q: 'thing', **product_options}, # Model with implied index
'blurbs' => { q: 'happy' }, # Index not backed by a model, results will be simple hashes
**other_searches
)
```
Initially I expected that the return type would be a simple array, however this might not be ideal since it
- does not provide a performant way to use only the results of a single search
- does not …

Support Multi-Search

---

README.md

Just something I noticed while editing `README.md`: `## Sorted search` seems to logically belong under `## Custom search` but it has the same level of heading (and does not have its place in the TOC).

Demote sorted search to level 3 heading

---

lib/meilisearch/rails/multi_search/result.rb

Fix the each_result method for multi search requests to pass a block to the each method.

fix: use block for each_result in multi_search

---

lib/meilisearch-rails.rb
lib/meilisearch/rails/ms_clean_up_job.rb
spec/system/tech_shop_spec.rb

N/A
- fixed deprecated warnings from meilisearch-ruby methods.

Fixed soft_deprecate warnings in meilisearch-ruby

---

.rubocop.yml
spec/spec_helper.rb

Rubocop's config was still enforcing ruby 2 code style. This is just a step that was missing in #367.

Target ruby 3 with rubocop

---

.github/workflows/tests.yml
Gemfile
bors.toml
meilisearch-rails.gemspec
playground/Dockerfile
playground/Gemfile
playground/config/application.rb

We should be able to run the CI after this PR.
Deprecate ruby 3.0 and 3.1 officially from the CI and add support to ruby 3.4

Fix CI for after ubuntu-latest becomes ubuntu-24

---

meilisearch-rails.gemspec

twiddle-wakka (~>) operator is not meant only for minor versions, its behavior depends on how you specify the version. ~> 0.28 will grab anything >= 0.28 and < 1, while ~> 0.28.0 will grab >= 0.28.0 to < 0.29.
For more information, see https://github.com/meilisearch/meilisearch-rails/issues/386 .
Fixes #386

Properly constrain version of meilisearch ruby gem

---

lib/meilisearch/rails/pagination/kaminari.rb
spec/pagination/kaminari_spec.rb

Fixes regression in #376
Fixes #394

Properly set `limit` in Kaminari

---

README.md
lib/meilisearch/rails/multi_search.rb
lib/meilisearch/rails/multi_search/result.rb
spec/multi_search/result_spec.rb
spec/multi_search_spec.rb

Fixes #364
Todo:
Two more issues remain in multi search after gets completed: #362 and #389

Allow custom group names in multi search

---

README.md
lib/meilisearch/rails/multi_search.rb
spec/multi_search_spec.rb

Made a mistake when supporting this option, at least it has not made it to release yet.

Rename index_name option to index_uid in multi_search

---

spec/spec_helper.rb

This allows rspec to "remember" the last test run, allowing for commands like `rspec --only-failures`, which should improve developer UX.
Picked `spec/tmp/examples.txt` since it's idiomatic to call this file examples.txt and `spec/tmp` was already in the gitignore.
It's a small thing but I don't think there's an argument against having it.

Add rspec status persistence file

---

README.md
lib/meilisearch/rails/multi_search.rb
lib/meilisearch/rails/multi_search/result.rb
spec/multi_search_spec.rb

Fixes part of #397
- This makes multi_search, like the regular search, support relations and other collections that respond to `where`.
- In favor of this new :collection option, :class_name is softly deprecated for a consistent user experience (since :collection does everything that :class_name did and more)

Support scopes in multi_search

---

.gitignore
spec/spec_helper.rb
spec/support/active_record_schema.rb
spec/support/sequel_db.rb

Please see the descriptions of each commit for explanations.

Remove legacy code in specs
